//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hack_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainData
    {
        public string Date { get; set; }
        public string Who { get; set; }
        public string Station { get; set; }
        public string Object { get; set; }
        public string TimeStart { get; set; }
        public string DateEnd { get; set; }
        public string TimeEnd { get; set; }
        public string Ind { get; set; }
        public Nullable<int> Count { get; set; }
        public string Service { get; set; }
        public string Why { get; set; }
        public string WhoDoing { get; set; }
        public string WhoDateEnd { get; set; }
        public string WhoTimeEnd { get; set; }
        public int id { get; set; }
    }
}
